export const MEDIDAS_LIST_REQUEST = 'MEDIDAS_LIST_REQUEST';
export const MEDIDAS_LIST_SUCCESS = 'MEDIDAS_LIST_SUCCESS';
export const MEDIDAS_LIST_FAIL = 'MEDIDAS_LIST_FAIL';

export const MEDIDAS_CREATE_REQUEST = 'MEDIDAS_CREATE_REQUEST';
export const MEDIDAS_CREATE_SUCCESS = 'MEDIDAS_CREATE_SUCCESS';
export const MEDIDAS_CREATE_FAIL = 'MEDIDAS_CREATE_FAIL';

export const MEDIDAS_UPDATE_REQUEST = 'MEDIDAS_UPDATE_REQUEST';
export const MEDIDAS_UPDATE_SUCCESS = 'MEDIDAS_UPDATE_SUCCESS';
export const MEDIDAS_UPDATE_FAIL = 'MEDIDAS_UPDATE_FAIL';

export const MEDIDAS_DELETE_REQUEST = 'MEDIDAS_DELETE_REQUEST';
export const MEDIDAS_DELETE_SUCCESS = 'MEDIDAS_DELETE_SUCCESS';
export const MEDIDAS_DELETE_FAIL = 'MEDIDAS_DELETE_FAIL';

